export {
  canonicalizeGraphSnapshot,
  canonicalizeDiagnostic,
  canonicalizeEvidence,
  canonicalizeGraphEdge,
  canonicalizeGraphNode,
  assertSupportedSchemaVersion,
  createGraphSnapshot,
  GraphContractError,
  GraphValidationError,
  GraphSchemaVersionError,
  parseGraphSnapshot,
  serializeGraphSnapshot,
  stableStringify,
  type GraphValidationIssue,
} from "./canonical.js";
export {
  canonicalizeGraphDiff,
  diffGraphSnapshots,
  diffSnapshots,
  parseGraphDiff,
  serializeGraphDiff,
  type GraphDiffOptions,
} from "./diff.js";
export {
  canonicalizeGraphTopology,
  GraphLayerDefinitionSchema,
  GraphTopologyOptionsSchema,
  GraphTopologyValidationError,
  serializeGraphTopology,
  summarizeGraphTopology,
  type GraphLayerDefinition,
  type GraphTopologyOptions,
} from "./topology.js";
export {
  computeForwardImpact,
  computeImpactSubgraph,
  computeReverseImpact,
  ImpactDirectionSchema,
  ImpactQuerySchema,
  serializeImpactSubgraph,
  type ImpactCycle,
  type ImpactDirection,
  type ImpactEdge,
  type ImpactNode,
  type ImpactQuery,
  type ImpactSubgraph,
  type ImpactTraversalOptions,
} from "./impact.js";
export {
  ARCHITECTURE_IMPACT_CONTRACT,
  ARCHITECTURE_IMPACT_SCHEMA_VERSION,
  ArchitectureImpactAffectedNodeSchema,
  ArchitectureImpactAssessmentSchema,
  ArchitectureImpactReasonCodeSchema,
  ArchitectureImpactReasonSchema,
  ArchitectureImpactScenarioSchema,
  ArchitectureImpactTraversedEdgeSchema,
  ArchitectureImpactUnknownCodeSchema,
  ArchitectureImpactUnknownSchema,
  ArchitectureImpactUncertaintyCodeSchema,
  ArchitectureImpactUncertaintySchema,
  ImpactBoundarySchema,
  ImpactChangeKindSchema,
  ImpactChangeSchema,
  ImpactConfidenceSchema,
  ImpactDirectionSchema as ArchitectureImpactDirectionSchema,
  ImpactEdgeKindSchema,
  ImpactNodeKindSchema,
  ImpactTraversalRuleSchema,
  assessArchitectureImpact,
  serializeArchitectureImpactAssessment,
  type ArchitectureImpactAffectedNode,
  type ArchitectureImpactAssessment,
  type ArchitectureImpactReason,
  type ArchitectureImpactScenario,
  type ArchitectureImpactTraversedEdge,
  type ArchitectureImpactUnknown,
  type ArchitectureImpactUncertainty,
  type ImpactBoundary,
  type ImpactChange,
  type ImpactChangeKind,
  type ImpactConfidence,
  type ImpactDirection as ArchitectureImpactDirection,
  type ImpactEdgeKind,
  type ImpactNodeKind,
  type ImpactTraversalRule,
} from "./impact-model.js";
export {
  ARCHITECTURE_QUERY_CONTRACT,
  ARCHITECTURE_QUERY_SCHEMA_VERSION,
  ARCHITECTURE_QUERY_SUPPORTED_OPERATIONS,
  ARCHITECTURE_QUERY_UNSUPPORTED_OPERATIONS,
  ArchitectureQueryDiagnosticSchema,
  ArchitectureQueryEdgePredicateSchema,
  ArchitectureQueryEdgeSchema,
  ArchitectureQueryEvidenceSchema,
  ArchitectureQueryLimitsSchema,
  ArchitectureQueryPaginationSchema,
  ArchitectureQueryPaginationResultSchema,
  ArchitectureQueryBoundarySchema,
  ArchitectureQueryCycleSchema,
  ArchitectureQueryNodePredicateSchema,
  ArchitectureQueryNodeDepthSchema,
  ArchitectureQueryNodeReferenceSchema,
  ArchitectureQueryOperationSchema,
  ArchitectureQueryOrderingSchema,
  ArchitectureQueryPathResultSchema,
  ArchitectureQueryPathSchema,
  ArchitectureQueryProjectionSchema,
  ArchitectureQueryResultSchema,
  ArchitectureQuerySchema,
  ArchitectureQuerySelectorSchema,
  ArchitectureQueryStatusSchema,
  ArchitectureQueryTraversalSchema,
  executeArchitectureQuery,
  parseArchitectureQuery,
  serializeArchitectureQuery,
  serializeArchitectureQueryResult,
  type ArchitectureQuery,
  type ArchitectureQueryBoundary,
  type ArchitectureQueryCycle,
  type ArchitectureQueryDiagnostic,
  type ArchitectureQueryEdge,
  type ArchitectureQueryEdgePredicate,
  type ArchitectureQueryEvidence,
  type ArchitectureQueryNodePredicate,
  type ArchitectureQueryNodeDepth,
  type ArchitectureQueryPagination,
  type ArchitectureQueryPaginationResult,
  type ArchitectureQueryMetadata,
  type ArchitectureQueryNodeReference,
  type ArchitectureQueryOperation,
  type ArchitectureQueryPath,
  type ArchitectureQueryPathResult,
  type ArchitectureQueryResult,
  type ArchitectureQueryStatus,
} from "./query.js";
export {
  ARCHITECTURE_QUERY_EXPLANATION_CONTRACT,
  ARCHITECTURE_QUERY_EXPLANATION_SCHEMA_VERSION,
  ARCHITECTURE_QUERY_EXPLANATION_TOOL_VERSION,
  ArchitectureQueryExplanationSchema,
  ArchitectureQueryExplanationSummarySchema,
  ArchitectureQueryExplanationToolSchema,
  ArchitectureQueryExplanationUncertaintyCodeSchema,
  ArchitectureQueryExplanationUncertaintySchema,
  buildArchitectureQueryExplanation,
  explainArchitectureQuery,
  serializeArchitectureQueryExplanation,
  type ArchitectureQueryExplanation,
  type ArchitectureQueryExplanationSummary,
  type ArchitectureQueryExplanationTool,
  type ArchitectureQueryExplanationUncertainty,
  type ArchitectureQueryExplanationUncertaintyCode,
} from "./query-explanation.js";
export {
  ARCHITECTURE_QUERY_ADR_DIAGNOSTIC_CODES,
  ARCHITECTURE_QUERY_METADATA_CONTRACT,
  ARCHITECTURE_QUERY_METADATA_SCHEMA_VERSION,
  ARCHITECTURE_QUERY_OWNERSHIP_HINT_CONTRACT,
  ArchitectureQueryAdrDiagnosticSchema,
  ArchitectureQueryMetadataDecisionInputSchema,
  ArchitectureQueryMetadataDiagnosticSchema,
  ArchitectureQueryMetadataInputSchema,
  ArchitectureQueryMetadataOwnershipInputSchema,
  ArchitectureQueryMetadataPolicyInputSchema,
  ArchitectureQueryMetadataResultSchema,
  ArchitectureQueryMetadataUnsupportedSchema,
  ArchitectureQueryOwnershipHintSchema,
  parseArchitectureQueryMetadata,
  projectArchitectureQueryMetadata,
  type ArchitectureQueryMetadataDiagnostic,
  type ArchitectureQueryMetadataDecisionProjection,
  type ArchitectureQueryMetadataInput,
  type ArchitectureQueryMetadataOwnershipProjection,
  type ArchitectureQueryMetadataPolicyProjection,
  type ArchitectureQueryMetadataResult,
  type ArchitectureQueryOwnershipHint,
} from "./query-metadata.js";
export {
  IdentityMatchConfidenceSchema,
  IdentityMatchMethodSchema,
  IdentityMatchSchema,
  IdentitySignalSchema,
  IdentityAmbiguitySchema,
  IdentityCandidateSchema,
  GraphDiffIdentitySchema,
  IdentityUnsupportedSchema,
  IdentityPathHistorySchema,
  matchGraphNodeIdentities,
  reconcileGraphNodeIdentities,
  serializeIdentityReconciliation,
  type IdentityAmbiguity,
  type IdentityCandidate,
  type GraphDiffIdentity,
  type IdentityUnsupported,
  type IdentityMatch,
  type IdentityMatchConfidence,
  type IdentityMatchMethod,
  type IdentityPathHistory,
  type IdentityReconciliationOptions,
  type IdentityReconciliation,
  type IdentitySignal,
} from "./identity.js";
export {
  WORKSPACE_IDENTITY_CONTRACT,
  WORKSPACE_IDENTITY_MAX_AMBIGUITIES,
  WORKSPACE_IDENTITY_MAX_COMPOSED_KEY_LENGTH,
  WORKSPACE_IDENTITY_MAX_NODES,
  WORKSPACE_IDENTITY_MAX_ORIGIN_ALIASES,
  WORKSPACE_IDENTITY_MAX_ORIGIN_LENGTH,
  WORKSPACE_IDENTITY_MAX_REPOSITORIES,
  WORKSPACE_IDENTITY_MAX_REPOSITORY_ALIASES,
  WORKSPACE_IDENTITY_SCHEMA_VERSION,
  WorkspaceComposedIdentitySchema,
  WorkspaceIdentityAmbiguityKindSchema,
  WorkspaceIdentityAmbiguitySchema,
  WorkspaceIdentityCompositionSchema,
  WorkspaceIdentityNamespaceSchema,
  WorkspaceIdentityRepositorySchema,
  WorkspaceIdentityResolutionSchema,
  WorkspaceIdentitySnapshotSchema,
  WorkspaceIdentityValidationError,
  WorkspaceOriginMetadataSchema,
  composeWorkspaceIdentities,
  composeWorkspaceIdentity,
  composeWorkspaceIdentityNamespaces,
  parseWorkspaceIdentityComposition,
  serializeWorkspaceIdentityComposition,
  type WorkspaceComposedIdentity,
  type WorkspaceIdentityAmbiguity,
  type WorkspaceIdentityAmbiguityKind,
  type WorkspaceIdentityComposition,
  type WorkspaceIdentityCompositionOptions,
  type WorkspaceIdentityErrorCode,
  type WorkspaceIdentityNamespace,
  type WorkspaceIdentityRepository,
  type WorkspaceIdentityResolution,
  type WorkspaceIdentitySnapshot,
  type WorkspaceOriginMetadata,
} from "./workspace-identity.js";
export {
  assertCompatibleCapabilityRegistryVersion,
  assertSupportedCapabilityRegistryVersion,
  CAPABILITY_REGISTRY,
  CAPABILITY_REGISTRY_VERSION,
  CapabilityRegistrySchema,
  CapabilityRegistryVersionError,
  type Capability,
  type CapabilityConfidence,
  type CapabilityRegistry,
  type ExtractorCapability,
} from "./capabilities.js";
export {
  DIAGNOSTIC_REGISTRY,
  DIAGNOSTIC_REGISTRY_VERSION,
  DiagnosticRegistrySchema,
  getDiagnosticDefinition,
  type DiagnosticDefinition,
  type DiagnosticRegistry,
  type DiagnosticSeverity,
} from "./diagnostics.js";
export {
  CARTOGRAPH_CONFIG_SCHEMA_VERSION,
  CartographConfigSchema,
  ConfigValidationError,
  defaultCartographConfig,
  parseCartographConfig,
  readCartographConfig,
  type CartographConfig,
  type ConfigUnknownFieldMode,
  type ParsedCartographConfig,
  type ResourceLimits,
} from "./config.js";
export {
  DiagnosticSchema,
  DiffComparisonModeSchema,
  DiffComparisonSchema,
  EdgeChangeClassificationSchema,
  EvidenceSchema,
  GraphDiffSchema,
  GraphDiffTopologySchema,
  GraphDiffSummarySchema,
  GraphEdgeSchema,
  GraphTopologySummarySchema,
  GraphNodeSchema,
  GraphSnapshotSchema,
  RewiredEdgeSchema,
  RevisionSchema,
  SourceLocationSchema,
  GRAPH_DIFF_SCHEMA_VERSION,
  GRAPH_SNAPSHOT_SCHEMA_VERSION,
  type GraphTopologySummary,
} from "./schemas.js";
export {
  migrateGraphSnapshot,
  serializeMigrationReport,
  SnapshotMigrationError,
  validateMigrationOutput,
  type IdentityMigrationRecord,
  type SnapshotMigrationReport,
  type SnapshotMigrationResult,
} from "./migrations.js";
export {
  AdapterConformanceError,
  runAdapterConformance,
  type AdapterConformanceCase,
  type AdapterConformanceCaseReport,
  type AdapterConformanceExpectation,
  type AdapterConformanceIdentityCase,
  type AdapterConformanceIdentityReport,
  type AdapterConformanceOptions,
  type AdapterConformanceReport,
} from "./adapter-conformance.js";
export {
  assertSupportedEnvironment,
  currentSupportEnvironment,
  SUPPORT_MATRIX_CONTRACT,
  SUPPORT_MATRIX_DIAGNOSTIC_CODE,
  SUPPORT_MATRIX_SCHEMA_VERSION,
  SUPPORTED_NODE_LTS,
  SUPPORTED_NODE_MINIMUM,
  SUPPORTED_PLATFORMS,
  UnsupportedEnvironmentError,
  type SupportEnvironment,
  type SupportEnvironmentReport,
  type SupportedNodeLts,
  type SupportedPlatform,
} from "./support.js";
export {
  createPolicyBundle,
  CURRENT_POLICY_BUNDLE_COMPATIBILITY,
  importPolicyBundle,
  parsePolicyBundle,
  POLICY_BUNDLE_CONTRACT,
  POLICY_BUNDLE_MEDIA_TYPE,
  POLICY_BUNDLE_SCHEMA_VERSION,
  PolicyBundleAuthoritySchema,
  PolicyBundleCompatibilitySchema,
  PolicyBundleSchema,
  PolicyBundleVerificationError,
  PolicyRuleSchema,
  PolicySchema,
  PolicySourceSchema,
  policySourceDigest,
  PolicyBundleDraftSchema,
  serializePolicyBundle,
  verifyPolicyBundle,
  type Policy,
  type PolicyBundle,
  type PolicyBundleAuthority,
  type PolicyBundleCompatibility,
  type PolicyBundleDraft,
  type PolicyBundleErrorCode,
  type PolicyBundleVerification,
  type PolicyRule,
  type PolicySource,
  type VerifyPolicyBundleOptions,
} from "./policy-bundles.js";
export {
  evaluatePolicyBundleMigration,
  migratePolicyBundle,
  POLICY_BUNDLE_MIGRATION_CONTRACT,
  POLICY_BUNDLE_MIGRATION_SCHEMA_VERSION,
  PolicyBundleMigrationError,
  PolicyBundleMigrationReportSchema,
  PolicyBundleRevocationListSchema,
  serializePolicyBundleMigrationReport,
  type EvaluatePolicyBundleMigrationOptions,
  type PolicyBundleMigrationErrorCode,
  type PolicyBundleMigrationFinding,
  type PolicyBundleMigrationReport,
  type PolicyBundleRevocationList,
} from "./policy-bundle-migrations.js";
export {
  LOCAL_POLICY_CONTRACT,
  LOCAL_POLICY_EXCEPTION_CONTRACT,
  LOCAL_POLICY_EXCEPTION_SCHEMA_VERSION,
  LOCAL_POLICY_ADR_BINDING_CONTRACT,
  LOCAL_POLICY_ADR_BINDING_SCHEMA_VERSION,
  LOCAL_POLICY_SCHEMA_VERSION,
  POLICY_CONFIG_MAX_BYTES,
  PolicyConfigSchema,
  PolicyConfigValidationError,
  LocalPolicyDiffSelectorSchema,
  LocalPolicyEdgeSelectorSchema,
  LocalPolicyExceptionSchema,
  LocalPolicyExceptionScopeSchema,
  LocalPolicyAdrBindingRequirementSchema,
  LocalPolicyAdrBindingSchema,
  LocalPolicyIncludeSchema,
  LocalPolicyNodeSelectorSchema,
  LocalPolicyPathSchema,
  LocalPolicyRuleSchema,
  parsePolicyConfig,
  readPolicyConfig,
  serializePolicyConfig,
  type PolicyConfig,
  type LocalPolicyDiffSelector,
  type LocalPolicyEdgeSelector,
  type LocalPolicyException,
  type LocalPolicyExceptionScope,
  type LocalPolicyAdrBinding,
  type LocalPolicyAdrBindingRequirement,
  type LocalPolicyInclude,
  type LocalPolicyNodeSelector,
  type LocalPolicyRule,
} from "./policy.js";
export {
  ADR_DOCUMENT_MAX_BYTES,
  ADR_REFERENCE_CONTRACT,
  ADR_REFERENCE_DIAGNOSTIC_CODES,
  ADR_REFERENCE_MAX_BYTES,
  ADR_REFERENCE_SCHEMA_VERSION,
  AdrDateTimeSchema,
  AdrLifecycleTransitionSchema,
  AdrReferenceDiagnosticCodeSchema,
  AdrReferenceDocumentSchema,
  AdrReferenceSchema,
  AdrReferenceValidationError,
  AdrStatusSchema,
  parseAdrReferenceDocument,
  readAdrReferenceDocument,
  serializeAdrGraphEdgeId,
  serializeAdrReferenceDocument,
  validateAdrLifecycle,
  validateAdrReferences,
  type AdrDateTime,
  type AdrLifecycleTransition,
  type AdrReference,
  type AdrReferenceDiagnostic,
  type AdrReferenceDiagnosticCode,
  type AdrReferenceDocument,
  type AdrReferenceValidationOptions,
  type AdrReferenceValidationResult,
  type AdrStatus,
} from "./adr.js";
export {
  evaluatePolicy,
  evaluatePolicyConfig,
  evaluatePolicyOnDiff,
  evaluatePolicyOnSnapshot,
  POLICY_EVALUATION_CONTRACT,
  POLICY_EVALUATION_SCHEMA_VERSION,
  POLICY_EXCEPTION_EXPIRING_WINDOW_DAYS,
  PolicyEvaluationError,
  PolicyEvaluationSchema,
  PolicyExceptionReportSchema,
  PolicyExceptionStatusSchema,
  PolicyUnsupportedSchema,
  PolicyViolationSchema,
  serializePolicyEvaluation,
  type PolicyEvaluation,
  type PolicyEvaluationInput,
  type PolicyEvaluationOptions,
  type PolicyAdrContext,
  type PolicyExceptionReport,
  type PolicyUnsupported,
  type PolicyViolation,
} from "./policy-evaluation.js";
export {
  composePolicyConfig,
  POLICY_COMPOSITION_CONTRACT,
  POLICY_COMPOSITION_MAX_DEPTH,
  POLICY_COMPOSITION_MAX_FILES,
  POLICY_COMPOSITION_MAX_OVERRIDES,
  POLICY_COMPOSITION_MAX_RULES,
  POLICY_COMPOSITION_SCHEMA_VERSION,
  PolicyCompositionError,
  PolicyCompositionSchema,
  serializePolicyComposition,
  type PolicyComposition,
  type PolicyCompositionErrorCode,
  type PolicyCompositionOverride,
  type PolicyCompositionSource,
} from "./policy-composition.js";
export {
  WORKSPACE_COMPOSITION_CONTRACT,
  WORKSPACE_COMPOSITION_MAX_BOUNDARIES,
  WORKSPACE_COMPOSITION_MAX_MANIFEST_BYTES,
  WORKSPACE_COMPOSITION_MAX_OMISSIONS,
  WORKSPACE_COMPOSITION_MAX_REPOSITORIES,
  WORKSPACE_COMPOSITION_MAX_SNAPSHOT_BYTES,
  WORKSPACE_COMPOSITION_MAX_TOTAL_SNAPSHOT_BYTES,
  WORKSPACE_COMPOSITION_SCHEMA_VERSION,
  WorkspaceBoundarySchema,
  WorkspaceCompositionLimitsSchema,
  WorkspaceCompositionManifestSchema,
  WorkspaceCompositionValidationError,
  WorkspaceLocalFileSchema,
  WorkspaceLocalPathSchema,
  WorkspaceManifestSchema,
  WorkspaceOmissionSchema,
  WorkspaceRepositorySchema,
  WorkspaceRepositorySnapshotSchema,
  parseWorkspaceCompositionManifest,
  parseWorkspaceManifest,
  readWorkspaceCompositionManifest,
  serializeWorkspaceCompositionManifest,
  serializeWorkspaceManifest,
  validateWorkspaceCompositionManifest,
  type WorkspaceBoundary,
  type WorkspaceCompositionErrorCode,
  type WorkspaceCompositionLimits,
  type WorkspaceCompositionManifest,
  type WorkspaceLocalPath,
  type WorkspaceManifest,
  type WorkspaceOmission,
  type WorkspaceRepository,
  type WorkspaceRepositorySnapshot,
} from "./workspace-composition.js";
export {
  WORKSPACE_BOUNDARY_CONTRACT,
  WORKSPACE_BOUNDARY_MAX_CANDIDATES,
  WORKSPACE_BOUNDARY_MAX_CYCLES,
  WORKSPACE_BOUNDARY_MAX_DECLARATIONS,
  WORKSPACE_BOUNDARY_MAX_DIAGNOSTICS,
  WORKSPACE_BOUNDARY_MAX_EDGES,
  WORKSPACE_BOUNDARY_MAX_EVIDENCE_PER_RECORD,
  WORKSPACE_BOUNDARY_MAX_EVIDENCE_SOURCES,
  WORKSPACE_BOUNDARY_MAX_OMISSIONS,
  WORKSPACE_BOUNDARY_MAX_NODES,
  WORKSPACE_BOUNDARY_MAX_REFERENCES,
  WORKSPACE_BOUNDARY_MAX_REPOSITORIES,
  WORKSPACE_BOUNDARY_MAX_SNAPSHOT_EDGES,
  WORKSPACE_BOUNDARY_SCHEMA_VERSION,
  WorkspaceBoundaryCandidateSchema,
  WorkspaceBoundaryCompositionSchema,
  WorkspaceBoundaryDeclarationSchema,
  WorkspaceBoundaryEdgeSchema,
  WorkspaceBoundaryEvidenceSourceSchema,
  WorkspaceBoundaryOmissionSchema,
  WorkspaceBoundaryProvenanceSchema,
  WorkspaceBoundaryReferenceSchema,
  WorkspaceBoundaryRepositorySchema,
  WorkspaceBoundaryRepositorySummarySchema,
  WorkspaceBoundaryResolutionSchema,
  WorkspaceBoundaryTargetSchema,
  WorkspaceBoundaryRequestSchema,
  WorkspaceBoundaryCycleSchema,
  WorkspaceBoundaryValidationError,
  parseWorkspaceBoundaryComposition,
  resolveWorkspaceBoundaries,
  resolveWorkspaceBoundary,
  resolveWorkspaceBoundaryReferences,
  serializeWorkspaceBoundaryComposition,
  type WorkspaceBoundaryCandidate,
  type WorkspaceBoundaryComposition,
  type WorkspaceBoundaryDeclaration,
  type WorkspaceBoundaryEdge,
  type WorkspaceBoundaryEvidenceSource,
  type WorkspaceBoundaryErrorCode,
  type WorkspaceBoundaryOmission,
  type WorkspaceBoundaryProvenance,
  type WorkspaceBoundaryReference,
  type WorkspaceBoundaryRepository,
  type WorkspaceBoundaryRepositorySummary,
  type WorkspaceBoundaryResolution,
  type WorkspaceBoundaryResolutionOptions,
  type WorkspaceBoundaryTarget,
  type WorkspaceBoundaryRequest,
  type WorkspaceBoundaryCycle,
} from "./workspace-boundaries.js";
export {
  DEFAULT_WORKSPACE_RECOMPOSITION_LIMITS,
  WORKSPACE_RECOMPOSITION_CONTRACT,
  WORKSPACE_RECOMPOSITION_MAX_CACHE_BYTES,
  WORKSPACE_RECOMPOSITION_MAX_CACHE_ENTRIES,
  WORKSPACE_RECOMPOSITION_MAX_DEPENDENCIES,
  WORKSPACE_RECOMPOSITION_MAX_INPUTS,
  WORKSPACE_RECOMPOSITION_MAX_RESULT_BYTES,
  WORKSPACE_RECOMPOSITION_MAX_TEMP_ENTRIES,
  WORKSPACE_RECOMPOSITION_MAX_UNITS,
  WORKSPACE_RECOMPOSITION_SCHEMA_VERSION,
  WorkspaceRecompositionCacheEntrySchema,
  WorkspaceRecompositionCacheError,
  WorkspaceRecompositionCacheKeySchema,
  WorkspaceRecompositionCacheSchema,
  WorkspaceRecompositionInputSchema,
  WorkspaceRecompositionLimitsSchema,
  WorkspaceRecompositionPlanSchema,
  WorkspaceRecompositionPlanUnitSchema,
  WorkspaceRecompositionRequestSchema,
  WorkspaceRecompositionUnitSchema,
  WorkspaceRecompositionUnitStatusSchema,
  WorkspaceRecompositionValidationError,
  buildWorkspaceRecompositionKey,
  cleanupWorkspaceRecompositionCache,
  createWorkspaceRecompositionKey,
  parseWorkspaceRecompositionCache,
  parseWorkspaceRecompositionKey,
  parseWorkspaceRecompositionPlan,
  parseWorkspaceRecompositionRequest,
  planWorkspaceRecomposition,
  readWorkspaceRecompositionCache,
  recompositionPlan,
  recomposeWorkspace,
  removeWorkspaceRecompositionCache,
  serializeWorkspaceRecompositionCache,
  serializeWorkspaceRecompositionPlan,
  tryReadWorkspaceRecompositionCache,
  workspaceCacheKey,
  workspaceRecompositionDigest,
  writeWorkspaceCacheAtomic,
  writeWorkspaceRecompositionCacheAtomic,
  type WorkspaceRecompositionAtomicWriteOptions,
  type WorkspaceRecompositionCache,
  type WorkspaceRecompositionCacheEntry,
  type WorkspaceRecompositionCacheKey,
  type WorkspaceRecompositionComponentKind,
  type WorkspaceRecompositionErrorCode,
  type WorkspaceRecompositionInput,
  type WorkspaceRecompositionKeyComponent,
  type WorkspaceRecompositionLimits,
  type WorkspaceRecompositionPlan,
  type WorkspaceRecompositionPlanUnit,
  type WorkspaceRecompositionRequest,
  type WorkspaceRecompositionUnit,
  type WorkspaceRecompositionUnitStatus,
} from "./workspace-recomposition.js";
export {
  DEFAULT_WORKSPACE_PRIVACY_LIMITS,
  WORKSPACE_PRIVACY_CONTRACT,
  WORKSPACE_PRIVACY_MAX_BYTES,
  WORKSPACE_PRIVACY_MAX_CACHE_BYTES,
  WORKSPACE_PRIVACY_MAX_CACHE_ENTRIES,
  WORKSPACE_PRIVACY_MAX_COMPRESSED_BYTES,
  WORKSPACE_PRIVACY_MAX_EDGES,
  WORKSPACE_PRIVACY_MAX_EXPANDED_BYTES,
  WORKSPACE_PRIVACY_MAX_EXPANSION_RATIO,
  WORKSPACE_PRIVACY_MAX_DEPTH,
  WORKSPACE_PRIVACY_MAX_MEMORY_BYTES,
  WORKSPACE_PRIVACY_MAX_METADATA_FIELDS,
  WORKSPACE_PRIVACY_MAX_METADATA_VALUE_LENGTH,
  WORKSPACE_PRIVACY_MAX_NODES,
  WORKSPACE_PRIVACY_MAX_PATH_LENGTH,
  WORKSPACE_PRIVACY_MAX_PATHS,
  WORKSPACE_PRIVACY_MAX_REPORT_BYTES,
  WORKSPACE_PRIVACY_MAX_REPORT_ITEMS,
  WORKSPACE_PRIVACY_MAX_REPOSITORIES,
  WORKSPACE_PRIVACY_MAX_RUNTIME_METADATA_BYTES,
  WORKSPACE_PRIVACY_MAX_RUNTIME_METADATA_RECORDS,
  WORKSPACE_PRIVACY_MAX_TEMPORARY_ENTRIES,
  WORKSPACE_PRIVACY_MAX_WALL_CLOCK_MS,
  WORKSPACE_PRIVACY_SCHEMA_VERSION,
  WorkspacePrivacyAssessmentSchema,
  WorkspacePrivacyCacheSummarySchema,
  WorkspacePrivacyDiagnosticCodeSchema,
  WorkspacePrivacyDiagnosticSchema,
  WorkspacePrivacyLimitsSchema,
  WorkspacePrivacyObservedBudgetSchema,
  WorkspacePrivacyPathExposureSchema,
  WorkspacePrivacyReportSummarySchema,
  WorkspacePrivacyRepositorySchema,
  WorkspacePrivacyRequestSchema,
  WorkspacePrivacyRuntimeMetadataRecordSchema,
  WorkspacePrivacyRuntimeMetadataSchema,
  WorkspacePrivacySnapshotSummarySchema,
  WorkspacePrivacyTotalsSchema,
  WorkspacePrivacyValidationError,
  assessWorkspacePrivacy,
  assertWorkspacePrivacyPath,
  cleanupWorkspacePrivacyTemporaryDirectory,
  createWorkspacePrivacyBudget,
  createWorkspacePrivacyTemporaryDirectory,
  enforceWorkspacePrivacy,
  parseWorkspacePrivacyAssessment,
  parseWorkspacePrivacyRequest,
  serializeWorkspacePrivacyAssessment,
  serializeWorkspacePrivacyRequest,
  validateWorkspacePrivacyPath,
  validateWorkspacePrivacyRequest,
  withWorkspacePrivacyTempDirectory,
  withWorkspacePrivacyTemporaryDirectory,
  type WorkspacePrivacyAssessment,
  type WorkspacePrivacyBudget,
  type WorkspacePrivacyBudgetOptions,
  type WorkspacePrivacyCacheSummary,
  type WorkspacePrivacyDiagnostic,
  type WorkspacePrivacyDiagnosticCode,
  type WorkspacePrivacyErrorCode,
  type WorkspacePrivacyLimits,
  type WorkspacePrivacyObservedBudget,
  type WorkspacePrivacyPathExposure,
  type WorkspacePrivacyReportSummary,
  type WorkspacePrivacyRepository,
  type WorkspacePrivacyRequest,
  type WorkspacePrivacyRuntimeMetadata,
  type WorkspacePrivacyRuntimeMetadataRecord,
  type WorkspacePrivacySnapshotSummary,
  type WorkspacePrivacyTotals,
} from "./workspace-privacy.js";
export {
  parsePolicyCiMode,
  policyCiExitCode,
  POLICY_CI_EXIT_CODES,
  POLICY_CI_MODES,
  type PolicyCiMode,
} from "./policy-ci.js";
export {
  ADAPTER_COMPATIBILITY_CONTRACT,
  ADAPTER_COMPATIBILITY_MEDIA_TYPE,
  ADAPTER_COMPATIBILITY_REGISTRY,
  ADAPTER_COMPATIBILITY_SCHEMA_VERSION,
  AdapterCompatibilityContextSchema,
  AdapterCompatibilityMigrationSchema,
  AdapterCompatibilityRegistrySchema,
  AdapterCompatibilityResultSchema,
  AdapterCompatibilityStateSchema,
  AdapterCompatibilityTupleSchema,
  AdapterStabilitySchema,
  migrateAdapterManifest,
  migrateAdapterOutput,
  negotiateAdapterCompatibility,
  type AdapterCompatibilityContext,
  type AdapterCompatibilityMigration,
  type AdapterCompatibilityRegistry,
  type AdapterCompatibilityResult,
  type AdapterCompatibilityState,
  type AdapterCompatibilityTuple,
  type AdapterStability,
} from "./adapter-compatibility.js";
export {
  ADAPTER_API_VERSION,
  ADAPTER_CONTRACT,
  ADAPTER_MEDIA_TYPE,
  AdapterCapabilityDeclarationSchema,
  AdapterCapabilityManifestSchema,
  AdapterConfigSchema,
  AdapterExecutionPolicySchema,
  AdapterInputSchema,
  AdapterOutputSchema,
  AdapterResourceLimitsSchema,
  AdapterSourceInputSchema,
  AdapterValidationError,
  parseAdapterInput,
  parseAdapterManifest,
  parseAdapterOutput,
  runAdapter,
  serializeAdapterInput,
  serializeAdapterManifest,
  serializeAdapterOutput,
  validateAdapterOutputIntegrity,
  type AdapterCapabilityDeclaration,
  type AdapterCapabilityManifest,
  type AdapterConfig,
  type AdapterDiagnostic,
  type AdapterEvidence,
  type AdapterExecutionPolicy,
  type AdapterInput,
  type AdapterJsonValue,
  type AdapterOutput,
  type AdapterResourceLimits,
  type AdapterRevision,
  type AdapterSourceInput,
  type CartographAdapter,
} from "./adapters.js";
export {
  AdapterIsolationError,
  runAdapterIsolated,
  supportsAdapterIsolation,
  type AdapterIsolationErrorCode,
  type AdapterIsolationRequest,
  type IsolatedCartographAdapter,
} from "./adapter-isolation.js";
export {
  parseRuntimeTrace,
  parseRuntimeTraceJson,
  RUNTIME_TRACE_CONTRACT,
  RUNTIME_TRACE_FORMAT,
  RUNTIME_TRACE_MEDIA_TYPE,
  RUNTIME_TRACE_SCHEMA_VERSION,
  RuntimeSpanKindSchema,
  RuntimeSpanSchema,
  RuntimeSpanStatusSchema,
  RuntimeTraceLimitsSchema,
  RuntimeTraceSchema,
  RuntimeTraceSummarySchema,
  RuntimeTraceValidationError,
  serializeRuntimeTrace,
  type RuntimeSpan,
  type RuntimeSpanKind,
  type RuntimeSpanStatus,
  type RuntimeTrace,
  type RuntimeTraceLimits,
  type RuntimeTraceSummary,
  type RuntimeTraceValidationCode,
} from "./runtime-traces.js";
export {
  reconcileRuntimeTrace,
  RUNTIME_RECONCILIATION_CONTRACT,
  RUNTIME_RECONCILIATION_MEDIA_TYPE,
  RUNTIME_RECONCILIATION_SCHEMA_VERSION,
  RuntimeReconciliationClassificationSchema,
  RuntimeReconciliationError,
  RuntimeReconciliationInputSchema,
  RuntimeReconciliationRecordSchema,
  RuntimeReconciliationSchema,
  RuntimeReconciliationSummarySchema,
  RuntimeReconciliationUncertaintySchema,
  RuntimeSpanBindingSchema,
  serializeRuntimeReconciliation,
  type RuntimeReconciliation,
  type RuntimeReconciliationClassification,
  type RuntimeReconciliationErrorCode,
  type RuntimeReconciliationInput,
  type RuntimeReconciliationRecord,
  type RuntimeReconciliationRevision,
  type RuntimeReconciliationSummary,
  type RuntimeReconciliationUncertainty,
  type RuntimeSpanBinding,
} from "./runtime-reconciliation.js";
export {
  DEFAULT_RUNTIME_TRACE_SAFETY_POLICY,
  redactRuntimeTrace,
  RUNTIME_TRACE_SAFETY_CONTRACT,
  RUNTIME_TRACE_SAFETY_MEDIA_TYPE,
  RUNTIME_TRACE_SAFETY_SCHEMA_VERSION,
  RuntimeTraceRedactionFieldSchema,
  RuntimeTraceRedactionOptionsSchema,
  RuntimeTraceRetentionModeSchema,
  RuntimeTraceRetentionPolicySchema,
  RuntimeTraceRetentionStore,
  RuntimeTraceSafetyError,
  RuntimeTraceSafetyPolicySchema,
  serializeRuntimeTraceSafetyPolicy,
  type RuntimeTraceRedactionField,
  type RuntimeTraceRedactionOptions,
  type RuntimeTraceRetentionMode,
  type RuntimeTraceRetentionPolicy,
  type RuntimeTraceSafetyErrorCode,
  type RuntimeTraceSafetyPolicy,
} from "./runtime-trace-safety.js";
export {
  DEFAULT_RUNTIME_TRACE_BUDGET_POLICY,
  importRuntimeTraceWithBudget,
  RUNTIME_TRACE_BUDGETS_CONTRACT,
  RUNTIME_TRACE_BUDGETS_MEDIA_TYPE,
  RUNTIME_TRACE_BUDGETS_SCHEMA_VERSION,
  RuntimeTraceBudgetCoverageSchema,
  RuntimeTraceBudgetDiagnosticCodeSchema,
  RuntimeTraceBudgetDiagnosticSchema,
  RuntimeTraceBudgetError,
  RuntimeTraceBudgetOverflowSchema,
  RuntimeTraceBudgetPolicySchema,
  RuntimeTraceBudgetResultSchema,
  serializeRuntimeTraceBudgetResult,
  type RuntimeTraceBudgetCoverage,
  type RuntimeTraceBudgetDiagnostic,
  type RuntimeTraceBudgetDiagnosticCode,
  type RuntimeTraceBudgetErrorCode,
  type RuntimeTraceBudgetOverflow,
  type RuntimeTraceBudgetPolicy,
  type RuntimeTraceBudgetRedaction,
  type RuntimeTraceBudgetResult,
} from "./runtime-trace-budgets.js";
export {
  createRuntimeReconciliationReport,
  RUNTIME_RECONCILIATION_REPORT_CONTRACT,
  RUNTIME_RECONCILIATION_REPORT_MEDIA_TYPE,
  RUNTIME_RECONCILIATION_REPORT_SCHEMA_VERSION,
  RuntimeReconciliationBindingProvenanceSchema,
  RuntimeReconciliationCapabilityLimitationSchema,
  RuntimeReconciliationDiagnosticSchema,
  RuntimeReconciliationReportClassificationCountsSchema,
  RuntimeReconciliationReportCoverageSchema,
  RuntimeReconciliationReportLimitsSchema,
  RuntimeReconciliationReportSchema,
  RuntimeReconciliationRetentionSchema,
  RuntimeReconciliationRuntimeProvenanceSchema,
  RuntimeReconciliationStaticProvenanceSchema,
  RuntimeReconciliationUncertaintySummarySchema,
  serializeRuntimeReconciliationReport,
  type RuntimeReconciliationBindingProvenance,
  type RuntimeReconciliationCapabilityLimitation,
  type RuntimeReconciliationDiagnostic,
  type RuntimeReconciliationReport,
  type RuntimeReconciliationReportClassificationCounts,
  type RuntimeReconciliationReportCoverage,
  type RuntimeReconciliationReportInput,
  type RuntimeReconciliationReportLimits,
  type RuntimeReconciliationReportTraceCoverage,
  type RuntimeReconciliationReportTracePolicy,
  type RuntimeReconciliationRetention,
  type RuntimeReconciliationRuntimeProvenance,
  type RuntimeReconciliationStaticProvenance,
  type RuntimeReconciliationUncertaintySummary,
} from "./runtime-reconciliation-report.js";
export {
  assuranceSigningPayload,
  AssuranceSigningKeySchema,
  AssuranceSigningKeyringSchema,
  AssuranceSigningRecordSchema,
  AssuranceSigningVerificationError,
  AssuranceSigningVerificationReportSchema,
  ASSURANCE_SIGNING_ALGORITHM,
  ASSURANCE_SIGNING_ALGORITHM_VERSION,
  ASSURANCE_SIGNING_CONTRACT,
  ASSURANCE_SIGNING_SCHEMA_VERSION,
  evaluateAssuranceSigningRecord,
  serializeAssuranceSigningVerificationReport,
  verifyAssuranceSigningRecord,
  type AssuranceSigningKey,
  type AssuranceSigningKeyring,
  type AssuranceSigningRecord,
  type AssuranceSigningVerificationCode,
  type AssuranceSigningVerificationErrorCode,
  type AssuranceSigningVerificationReport,
  type VerifyAssuranceSigningOptions,
} from "./assurance-signing.js";
export {
  createRemediationSuggestion,
  generateRemediationSuggestions,
  remediationFindingDigest,
  REMEDIATION_SUGGESTION_CONTRACT,
  REMEDIATION_SUGGESTION_MAX_FINDINGS,
  REMEDIATION_SUGGESTION_MAX_SUGGESTIONS,
  REMEDIATION_SUGGESTION_SCHEMA_VERSION,
  RemediationEditSchema,
  RemediationEvidenceReferenceSchema,
  RemediationFindingInputSchema,
  RemediationFindingSchema,
  RemediationProposalSchema,
  RemediationRuleSchema,
  RemediationSuggestionError,
  RemediationSuggestionReportSchema,
  RemediationSuggestionSchema,
  RemediationSuggestionSkipSchema,
  RemediationSuggestionKindSchema,
  RemediationSuggestionRiskSchema,
  RemediationValidationStepSchema,
  serializeRemediationSuggestion,
  serializeRemediationSuggestionReport,
  type GenerateRemediationSuggestionsOptions,
  type RemediationEdit,
  type RemediationEvidenceReference,
  type RemediationFinding,
  type RemediationFindingInput,
  type RemediationRule,
  type RemediationProposal,
  type RemediationSkipReason,
  type RemediationSuggestion,
  type RemediationSuggestionErrorCode,
  type RemediationSuggestionKind,
  type RemediationSuggestionReport,
  type RemediationSuggestionRisk,
  type RemediationSuggestionSkip,
  type RemediationValidationStep,
} from "./remediation-suggestions.js";
export {
  defaultRemediationRuleCatalog,
  generateDeterministicRemediationSuggestions,
  remediationRuleCatalogDigest,
  REMEDIATION_RULESET_CONTRACT,
  REMEDIATION_RULESET_ID,
  REMEDIATION_RULESET_SCHEMA_VERSION,
  RemediationRuleCatalogEntrySchema,
  RemediationRuleCatalogSchema,
  serializeRemediationRuleCatalog,
  type GenerateDeterministicRemediationSuggestionsOptions,
  type RemediationRuleCatalog,
  type RemediationRuleCatalogEntry,
} from "./remediation-rules.js";
export {
  PATCH_PREVIEW_CONTRACT,
  PATCH_PREVIEW_MAX_OPERATIONS,
  PATCH_PREVIEW_MAX_REPLACEMENT_BYTES,
  PATCH_PREVIEW_SCHEMA_VERSION,
  patchContentDigest,
  patchPreviewRequestDigest,
  PatchPreviewAppliedOperationSchema,
  PatchPreviewError,
  PatchPreviewOperationSchema,
  PatchPreviewReportSchema,
  PatchPreviewRequestSchema,
  PatchPreviewValidationCommandSchema,
  PatchPreviewValidationResultSchema,
  previewPatch,
  serializePatchPreviewReport,
  type PatchPreviewAppliedOperation,
  type PatchPreviewErrorCode,
  type PatchPreviewOperation,
  type PatchPreviewOptions,
  type PatchPreviewReport,
  type PatchPreviewRequest,
  type PatchPreviewValidationCommand,
  type PatchPreviewValidationResult,
} from "./patch-previews.js";
export {
  createRemediationReview,
  remediationReviewRequestDigest,
  RemediationReviewDecisionSchema,
  RemediationReviewError,
  RemediationReviewEvidenceRevisionSchema,
  RemediationReviewExternalApplicationSchema,
  RemediationReviewFinalDispositionSchema,
  RemediationReviewSchema,
  RemediationReviewRequestSchema,
  RemediationReviewStateSchema,
  RemediationReviewValidationSchema,
  RemediationReviewValidationStatusSchema,
  serializeRemediationReview,
  REMEDIATION_REVIEW_CONTRACT,
  REMEDIATION_REVIEW_SCHEMA_VERSION,
  type CreateRemediationReviewOptions,
  type RemediationReview,
  type RemediationReviewDecision,
  type RemediationReviewErrorCode,
  type RemediationReviewRequest,
  type RemediationReviewState,
} from "./remediation-review.js";
export {
  REMEDIATION_EVALUATION_CONTRACT,
  REMEDIATION_EVALUATION_SCHEMA_VERSION,
} from "./remediation-evaluation.js";
export {
  FINDING_LIFECYCLE_CONTRACT,
  FINDING_LIFECYCLE_MEDIA_TYPE,
  FINDING_LIFECYCLE_MAX_EVENTS,
  FINDING_LIFECYCLE_MAX_EVIDENCE_REFS,
  FINDING_LIFECYCLE_MAX_FINDINGS,
  FINDING_LIFECYCLE_MAX_MIGRATIONS,
  FINDING_LIFECYCLE_SCHEMA_VERSION,
  FINDING_LIFECYCLE_STATES,
  FindingIdentityMigrationSchema,
  FindingIdentitySchema,
  FindingLifecycleActorSchema,
  FindingLifecycleDiagnosticSchema,
  FindingLifecycleEvidenceSchema,
  FindingLifecycleEventSchema,
  FindingLifecycleFindingResultSchema,
  FindingLifecycleInputSchema,
  FindingLifecycleProvenanceSchema,
  FindingLifecycleReportSchema,
  FindingLifecycleStateSchema,
  FindingLifecycleSummarySchema,
  FindingLifecycleValidationError,
  FindingRecordSchema,
  findingIdentityMigrationDigest,
  findingLifecycleEventDigest,
  findingLifecycleGenesisDigest,
  parseFindingLifecycleInput,
  parseFindingLifecycleReport,
  replayFindingLifecycle,
  serializeFindingLifecycleReport,
  type FindingIdentity,
  type FindingIdentityMigration,
  type FindingLifecycleActor,
  type FindingLifecycleDiagnostic,
  type FindingLifecycleEvidence,
  type FindingLifecycleEvent,
  type FindingLifecycleFindingResult,
  type FindingLifecycleInput,
  type FindingLifecycleProvenance,
  type FindingLifecycleReport,
  type FindingLifecycleState,
  type FindingLifecycleSummary,
  type FindingRecord,
} from "./finding-lifecycle.js";
export {
  OWNERSHIP_CONTRACT,
  OWNERSHIP_MAX_CODEOWNERS_BYTES,
  OWNERSHIP_MAX_OWNERS,
  OWNERSHIP_MAX_RULES_PER_SOURCE,
  OWNERSHIP_MAX_SOURCES,
  OWNERSHIP_MAX_TARGETS,
  OWNERSHIP_MEDIA_TYPE,
  OWNERSHIP_SCHEMA_VERSION,
  OwnershipDiagnosticSchema,
  OwnershipEvidenceSchema,
  OwnershipFallbackSchema,
  OwnershipMatchSchema,
  OwnershipOwnerSchema,
  OwnershipProvenanceSchema,
  OwnershipResolutionError,
  OwnershipResolutionInputSchema,
  OwnershipResolutionReportSchema,
  OwnershipResultSchema,
  OwnershipRuleSchema,
  OwnershipSourceSchema,
  OwnershipSummarySchema,
  OwnershipTargetSchema,
  parseCodeowners,
  parseOwnershipInput,
  parseOwnershipReport,
  resolveOwnership,
  serializeOwnershipReport,
  type OwnershipDiagnostic,
  type OwnershipEvidence,
  type OwnershipFallback,
  type OwnershipMatch,
  type OwnershipOwner,
  type OwnershipProvenance,
  type OwnershipResolutionInput,
  type OwnershipResolutionReport,
  type OwnershipResult,
  type OwnershipRule,
  type OwnershipSource,
  type OwnershipSummary,
  type OwnershipTarget,
  type ParseCodeownersOptions,
  type ParseCodeownersResult,
} from "./ownership.js";
export {
  SCIP_INTERCHANGE_CONTRACT,
  SCIP_INTERCHANGE_MEDIA_TYPE,
  SCIP_INTERCHANGE_MAX_DOCUMENTS,
  SCIP_INTERCHANGE_MAX_OCCURRENCES,
  SCIP_INTERCHANGE_MAX_RELATIONSHIPS,
  SCIP_INTERCHANGE_MAX_SYMBOLS,
  SCIP_INTERCHANGE_SCHEMA_VERSION,
  ScipDocumentMappingSchema,
  ScipDocumentSchema,
  ScipIndexSchema,
  ScipInterchangeReportSchema,
  ScipInterchangeValidationError,
  ScipMappingsSchema,
  ScipMetadataSchema,
  ScipOccurrenceSchema,
  ScipProvenanceSchema,
  ScipRelationshipMappingSchema,
  ScipRelationshipSchema,
  ScipSymbolInformationSchema,
  ScipSymbolMappingSchema,
  ScipToolInfoSchema,
  ScipUnsupportedFieldSchema,
  exportScipIndex,
  importScipIndex,
  parseScipIndex,
  serializeScipExport,
  serializeScipIndex,
  type ScipDocument,
  type ScipExportOptions,
  type ScipExportResult,
  type ScipImportResult,
  type ScipIndex,
  type ScipInterchangeReport,
  type ScipMappings,
  type ScipMetadata,
  type ScipOccurrence,
  type ScipProvenance,
  type ScipRelationship,
  type ScipSymbolInformation,
  type ScipToolInfo,
  type ScipUnsupportedField,
} from "./scip.js";
export type {
  ChangedDiagnostic,
  ChangedEdge,
  ChangedNode,
  DiffComparison,
  DiffComparisonMode,
  Diagnostic,
  EdgeChangeClassification,
  Evidence,
  FieldChange,
  GraphDiff,
  GraphDiffSummary,
  GraphEdge,
  GraphNode,
  GraphSnapshot,
  RewiredEdge,
  Revision,
  SourceLocation,
} from "./schemas.js";
