export {
  canonicalizeGraphSnapshot,
  canonicalizeDiagnostic,
  canonicalizeEvidence,
  canonicalizeGraphEdge,
  canonicalizeGraphNode,
  assertSupportedSchemaVersion,
  createGraphSnapshot,
  GraphContractError,
  GraphSchemaVersionError,
  parseGraphSnapshot,
  serializeGraphSnapshot,
  stableStringify,
} from "./canonical.js";
export {
  canonicalizeGraphDiff,
  diffGraphSnapshots,
  diffSnapshots,
  parseGraphDiff,
  serializeGraphDiff,
} from "./diff.js";
export {
  assertCompatibleCapabilityRegistryVersion,
  assertSupportedCapabilityRegistryVersion,
  CAPABILITY_REGISTRY,
  CAPABILITY_REGISTRY_VERSION,
  CapabilityRegistrySchema,
  CapabilityRegistryVersionError,
  type Capability,
  type CapabilityConfidence,
  type CapabilityRegistry,
  type ExtractorCapability,
} from "./capabilities.js";
export {
  CARTOGRAPH_CONFIG_SCHEMA_VERSION,
  CartographConfigSchema,
  ConfigValidationError,
  defaultCartographConfig,
  parseCartographConfig,
  readCartographConfig,
  type CartographConfig,
  type ConfigUnknownFieldMode,
  type ParsedCartographConfig,
  type ResourceLimits,
} from "./config.js";
export {
  DiagnosticSchema,
  EvidenceSchema,
  GraphDiffSchema,
  GraphEdgeSchema,
  GraphNodeSchema,
  GraphSnapshotSchema,
  RevisionSchema,
  SourceLocationSchema,
  GRAPH_DIFF_SCHEMA_VERSION,
  GRAPH_SNAPSHOT_SCHEMA_VERSION,
} from "./schemas.js";
export type {
  ChangedDiagnostic,
  ChangedEdge,
  ChangedNode,
  Diagnostic,
  Evidence,
  FieldChange,
  GraphDiff,
  GraphEdge,
  GraphNode,
  GraphSnapshot,
  Revision,
  SourceLocation,
} from "./schemas.js";
